### ISSUE TITLE
数据集下载

### ISSUE THREAD

**Issue by DannyGGBond** [ML-Song/Smoke-Detection#2]
“包含1000张图片的图片数据集(test8) http://smoke.ustc.edu.cn/datasets.htm”
“视频数据集 http://smoke.ustc.edu.cn/datasets.htm”
这两个数据集的网站打不开，应该是内网，请问可以其他的下载链接吗

**Comment by s-JoL** [comment]
不是内网，是网站不太稳定，我今天把数据集上传到百度云分享一下吧，希望给点个star

**Comment by DannyGGBond** [comment]
sure , thank you so much

**Comment by s-JoL** [comment]
分享至[google drive ](https://drive.google.com/file/d/1unBpfYyD1JGXAMz0A1Z5lQZNE9O6zj6R/view?usp=sharing)
