### ISSUE TITLE
請問一下，要如何取到smoke_dataset？

### ISSUE THREAD

**Issue by kaonick** [ML-Song/Smoke-Detection#3]
很感謝提供的範例，大部份功能都可執行，但就是沒辦法找到smoke_dataset中的資料集，能否指導一下，謝謝！

**Comment by s-JoL** [comment]
请参考readme中烟雾数据集部分，其中主要使用的test8已放在google cloud中可自行下载

**Comment by bao-O** [comment]
@ML-Song  Can you share this dataset via google drive? I can't access to this file on pan baidu right now. Thank in advance!
