### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by lianshi00** [ML-Song/Smoke-Detection#4]
首先 谢谢您的开源代码  学到很多 有一个小问题  test8中的数据集我可以下载 就是那个一千张图片 但是关于smoke dataset 里面的npy结尾文件的数据集我没有找到 请问这个是在哪里下载的 您有分享到google 云上么

**Comment by s-JoL** [comment]
这个在袁飞牛教授的主页有下载地址 http://staff.ustc.edu.cn/~yfn/index.html 的最后

**Comment by lianshi00** [comment]
OK thancs 找到了 复现了下 发现效果很好 想问下您做过有关火焰检测的案例么  我自己做过火焰的detection 效果并不是很好 感觉特征很不稳定～

**Comment by s-JoL** [comment]
不好意思，没有研究过这方面的。
不过中科大的火灾实验室好像有些这方面论文，你可以参考一下他们的工作。

**Comment by czb2133** [comment]
> OK thancs 找到了 复现了下 发现效果很好 想问下您做过有关火焰检测的案例么 我自己做过火焰的detection 效果并不是很好 感觉特征很不稳定～

您好 请问你运行VGG16的时候更改代码内容了么
