### ISSUE TITLE
npy文件是如何生成的

### ISSUE THREAD

**Issue by gschen** [ML-Song/Smoke-Detection#6]
您好，非常感谢代码分享，对于我的帮助是极大的。
        +--set1_48_data.npy
|       +--set1_48_label.npy
|       +--set2_48_data.npy
|       +--set2_48_label.npy
|       +--set3_48_data.npy
|       +--set3_48_label.npy
|       +--set4_48_data.npy
|       +--set4_48_label.npy

请问这些npy文件是代码生成的还是需要自己前往某个地址下载，如果需要自行下载，可以分享一个链接嘛？

非常感谢。

**Comment by s-JoL** [comment]
您好，这个数据集是由Feiniu Yuan组所收集
可以从这里下载 https://pan.baidu.com/s/1miva2HM
感谢您的关注
