### ISSUE TITLE
请问训练好了模型，如何检测烟雾视频，谢谢！

### ISSUE THREAD

**Issue by fuxinyu-smoke** [ML-Song/Smoke-Detection#8]

**Comment by s-JoL** [comment]
在python_files/raspberry_pi.py文件中包含了读取摄像头 调用烟雾检测模型以及显示的代码
如果你需要读取已有视频只需要把度摄像头改成读文件即可

**Comment by fuxinyu-smoke** [comment]
您好 ，因为看到亲  使用的模型是mobilenet的模型。我想使用混合模型（hog+lbp+vgg16迁移学习）进行检测，亲可以分享一下心得，或者上传一下脚本吗.万分感谢！
